config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "listings#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html\
  resources :listings, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :offers
    member do
      get :seller
    end
  end

  resources :users, only: :show do
    resources :listings, only: :index
    get :offers, to: "offers#user_index"
  end

  get "status", to: "offers#status"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :offers
  has_one_attached :photo

  validates :item_name, :item_description, :price, presence: true
  validates :item_name, uniqueness: true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :listing
  belongs_to :user

  validates :offer_price, :status, presence: true
  validates :status, inclusion: { in: %w[pending accepted rejected] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :listings
  has_many :offers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :all_user
  skip_before_action :authenticate_user!, only: :index
  def index
    if params[:query].present?
      sql_query = "item_name ILIKE :query OR item_description ILIKE :query"
      @listings = Listing.where(sql_query, query: "%#{params[:query]}%")
    else
      @listings = Listing.all
    end
  end
  
  def show
    @listing = Listing.find(params[:id])
    @listing.offers.each do |offer|
      if offer.user == current_user
        @offered = true
        @offered_price = offer.offer_price
      else
        @offered = false
      end
    end
  end

  def new
    @listing = Listing.new
  end

  def create
    listing = Listing.new(listing_params)
    listing.user = current_user
    listing.save
    redirect_to seller_listing_path(listing)
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    @listing.update(listing_params)
    redirect_to seller_listing_path(@listing)
  end

  def destroy
  end

  def seller
    @listings = Listing.where(user: current_user)
  end

  private

  def listing_params
    params.require(:listing).permit(:item_name, :item_description, :price, :user, :photo)
  end

  def all_user
    # delete this when we can have users
    @user = User.all
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @listing = Listing.find(params[:listing_id])
    @offers = Offer.all.where(listing_id: params[:listing_id])
  end

  def show
    @offer = Offer.find_by(listing_id: params[:listing_id])
  end

  def new
    @listing = Listing.find(params[:listing_id])
    @offer = Offer.new
  end

  def create
    listing = Listing.find(params[:listing_id])
    offer = Offer.new(offer_params)
    offer.user = current_user
    offer.listing = listing
    offer.status = "pending"
    if offer.save
      redirect_to user_offers_path(listing_id: listing.id, user_id: current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @listing = Listing.find(params[:listing_id])
    @offer = Offer.find(params[:id])
    @offer.status = params[:offer][:status]
    if @offer.save
      @listing.offers.map do |offer|
        unless offer.id == @offer.id
          offer.status = "rejected"
          offer.save!
        end
      end
    end
    redirect_to listing_offers_path(@listing)
  end

  def destroy
  end

  def sales
    current_user.listings
  end

  def status
    # @offer = Offer.find_by(listing_id: params[:listing_id])
    # @offer.update_attribute(:status, true)
  end

  def user_index
    @listings = Listing.find(current_user.offers.pluck(:listing_id).uniq)
  end

  private

  def offer_params
    params.require(:offer).permit(:offer_price)
  end

  def all_user
    # delete this when we can have users
    @user = User.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @listings = Listing.all
    @listings = @listings.last(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JplApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/listings/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-12">
      <div class="bg-white rounded p-3 shadow">
        <h1>Edit Listings</h1>
            <%= simple_form_for(@listing) do |f| %>
            <%= f.input :item_name %>
            <%= f.input :item_description %>
            <%= f.input :price %>
            <%= f.input :photo %>
            <%= f.submit class: "btn btn-red" %>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/listings/index.html.erb
<div class="d-flex py-2 px-2 pb-0">
  <%= form_with url: listings_path, method: :get, class: "d-flex w-100" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a listing"
    %>
    <%= submit_tag "Search", class: "btn btn-red" %>
  <% end %>
</div>

<br>
<div class="container">
  <div class="cover mb-0 d-flex align-items-center justify-content-center" style="background-image: url(<%= asset_path('Frame1.png') %>); width: 1150px; height: 325px; object-fit: cover;">
    </div>
  </div>
</div>


<div class="container">

<% @listings.each do |listing| %>
  <div class="card" id="list1" onmouseenter="showButton('list1')" onmouseleave="hideButton('list1')">
    <% if listing.photo.key? %>
      <%= cl_image_tag(listing.photo.key, class: "card__img")%>
    <% else %>
      <img src="https://picsum.photos/500/300/?building" alt="" class="card__img">
    <% end %>
    <div class="card__body">
      <h3 class="card__title"></i><%= listing.item_name %></h3>
      <div class="card__desc">
        <span class="card__desc__room"></i>Listed by: <%= listing.user.username %></span>
        <span class="card__desc__price"> <span class="card__desc__price--small"></span>$<%= listing.price %></span>
      </div>
    </div>
    <div>
      <%= link_to "View", listing_path(listing), class: "btn btn-whiteview w-100"%>
    </div>
  </div>
<% end %>
</div>

app/views/listings/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-12">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new Listing</h3>
          <%= simple_form_for(@listing) do |f| %>
            <%= f.input :item_name %>
            <%= f.input :item_description %>
            <%= f.input :price %>
            <%= f.input :photo %>
            <%= f.submit class: "btn btn-red" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/listings/seller.html.erb
<h2 class="text-center pt-5">All my listings</h2>

<div class="container">
  <% @listings.each do |listing| %>
    <div class="card" id="list1" onmouseenter="showButton('list1')" onmouseleave="hideButton('list1')">
      <% if listing.photo.key? %>
        <%= cl_image_tag(listing.photo.key, class: "card__img")%>
      <% else %>
        <img src="https://picsum.photos/500/300/?building" alt="" class="card__img">
      <% end %>
      <div class="card__body">
        <h3 class="card__title"></i><%= listing.item_name %></h3>
        <div class="card__desc">
          <span class="card__desc__room"></i>
          <% if listing.offers.any? %>
            <%= link_to "View Offers(#{listing.offers.size})", listing_offers_path(listing) %>
            <% listing.offers.each do |offer| %>
              <% if offer.status == "accepted" %>
                <i class="accepted">Sold!</i>
              <% end %>
            <% end %>
          <% else %>
            No Offer Yet
          <% end %>
          </span>
          <span class="card__desc__price"><span class="card__desc__price--small"></span>$<%= listing.price %></span><br>
        </div>
        <%= link_to "View Listing", listing_path(listing.id), class: "btn btn-red mt-3 w-100" %>
      </div>
    </div>
  <% end %>
</div>

app/views/listings/show.html.erb
<div class="container d-flex">
  <div class="row justify-content-center align-items-center border border-dark bg-light text-dark my-5 shadow-lg">
    <div class="col-12">
      <h2 class="text-center pt-5"><%= @listing.item_name %></h2><br>
      <% if @listing.photo.key? %>
        <%= cl_image_tag(@listing.photo.key, class: "listing-photo")%>
      <% else %>
        <img src="https://picsum.photos/500/300/?building" alt="" class="listing-photo">
      <% end %>
      <hr>
      <div>
      <div class="d-flex flex-column">
        <div class="p-2"><strong>Description: </strong><%= @listing.item_description %></div>
        <div class="p-2"><strong>Price: $</strong><%= @listing.price %></div>
        <div class="p-2"><strong>Listed by: </strong><%= @listing.user.username %></div>
      <% if @listing.user == current_user %>
        <div class="p-2 mb-2">
        <p><i>*This is your listed product.</i></p>
        <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-red w-100" %>
        </div>
        <% if @listing.offers.any? %>
          <div class="p-2 mb-2"><%= link_to "View Offers", listing_offers_path(@listing), class: "btn btn-whiteview w-100" %></div>
        <% end %>
      <% elsif @offered == true %>
        <div class="p-2 text-center">You offered <strong>$<%= @offered_price %></strong>, pending review.</div>
      <% else %>
        <%= link_to 'Offer', new_listing_offer_path(@listing), class: "btn btn-red mb-2" %><br>
      <% end %>

      <% if @listing.offers.any? %>
        <% @listing.offers.each do |offer| %>
          <% if offer.user == current_user %>
            <% if offer.status == "accepted" %>
              <div class="p-2 text-center bg-success text-white mb-2"><span>Status: <%= offer.status %></span></div>
            <% elsif offer.status == "pending" %>
              <div class="p-2 bg-secondary text-white mb-2"><span>Status: <%= offer.status %></span></div>
            <% elsif offer.status == "rejected" %>
              <div class="p-2 bg-danger text-white mb-2"><span>Status: <%= offer.status %></span></div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/offers/index.html.erb
<div class="container d-flex">
  <div class="row justify-content-center align-items-center">
  <h2 class="text-center pt-5">Received Offers</h2>
    <div class="col">
      <h3 class="pt-2"><%= @offers.first.listing.item_name %></h3><br>
      <% if @offers.first.listing.photo.key? %>
        <%= cl_image_tag(@offers.first.listing.photo.key, class: "listing-photo")%><br>
      <% else %>
        <img src="https://picsum.photos/500/300/?building" alt="" class="listing-photo"><br>
      <% end %>
      <div class="card__body">x
        <div class="card__desc__room">
          <span><%= @offers.first.listing.item_description %></span>
          <span class="card__desc__price"><span class="card__desc__price--small">$<%= @offers.first.listing.price %></span></span>
        </div>
      </div>
    </div>

    <div class="col p-3 mb-2 bg-light text-dark">
      <h4 class="mt-2"><%= @offers.size %> offers</h4><br>
      <ol>
      <% @offers.each_with_index do |offer, index| %>
        <li><%= offer.user.username %> offered $<%= offer.offer_price %>. Status:
        <% if offer.status == "accepted" %>
          <span class="accepted"><%= offer.status %></span></span>
        <% elsif offer.status == "pending" %>
          <span class="pending"><%= offer.status %></span></span>
        <% elsif offer.status == "rejected" %>
          <span class="rejected"><%= offer.status %></span></span>
        <% end %>
        <% if offer.status == "pending" %>
          <%= simple_form_for offer, url: listing_offer_path(@listing, offer) do |f| %>
              <%= f.hidden_field :status, :value => "accepted" %>
              <%= f.submit "Accept", class: "btn btn-green" %>
            <% end %>
          <% end %>
        </li><br>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-12">
      <div class="bg-white rounded p-3 shadow">
        <h1>Make an offer</h1>
            <%= simple_form_for [@listing, @offer] do |f| %>
            <%= f.input :offer_price, placeholder: "Listed Price: #{@listing.price}" %>
            <%= f.submit class: "btn btn-red" %>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/offers/sales.html.erb
Test

app/views/offers/status.html.erb
hello

app/views/offers/user_index.html.erb
<h2 class="text-center pt-5">Offers sent by me</h2>

<div class="container">
  <% @listings.each do |listing| %>
    <div class="card" id="list1" onmouseenter="showButton('list1')" onmouseleave="hideButton('list1')">
      <% if listing.photo.key? %>
        <%= cl_image_tag(listing.photo.key, class: "card__img")%>
      <% else %>
        <img src="https://picsum.photos/500/300/?building" alt="" class="card__img">
      <% end %>
      <div class="card__body">
        <h3 class="card__title"></i><%= listing.item_name %></h3>
        <div class="card__desc">
          <% listing.offers.each do |offer| %>
            <% if offer.user == current_user %>
              <span class="card__desc__room"></i>Your Offered Price: $<%= offer.offer_price %></span><br>
              <span class="card__desc__room"></i>Offer Status:
              <% if offer.status == "accepted" %>
                <span class="accepted"><%= offer.status %></span></span><br>
              <% elsif offer.status == "pending" %>
                <span class="pending"><%= offer.status %></span></span><br>
              <% elsif offer.status == "rejected" %>
                <span class="rejected"><%= offer.status %></span></span><br>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <%= link_to "View", listing_path(listing), class: "btn btn-whiteview stretched-link" %>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center" style="background-image: url(<%= asset_path("cover_pic.png") %>)">
  <div class="text-center">
    <h3 class="typed-js" data-controller="typed-js"><strong>Homepage</strong></h3>
  </div>
</div>

<div id="carouselWithControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/Users/williekoo/code/willkoo/jpl-app/app/assets/images/home01.png" class="d-block w-100" alt="Slide 1">
    </div>
    <div class="carousel-item">
      <img src="assets/images/bs-images/carousel-slide-2.png" class="d-block w-100" alt="Slide 2">
    </div>
    <div class="carousel-item">
      <img src="assets/images/bs-images/carousel-slide-3.png" class="d-block w-100" alt="Slide 3">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselWithControls" role="button" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselWithControls" role="button" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </a>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
  <%= link_to root_path do %>
    <%= image_tag "carousell-logo.png", alt: "alttext", class: "logo" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <li class="nav-item active mx-2">
          <%= link_to "Manage Listings", seller_listing_path(current_user), class: "nav-link" %>
        </li>
        <li>
          <%= link_to "Offers Sent", user_offers_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item active mx-2">
          <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete} , class: "dropdown-item nav-link" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item active mx-2">
        <%= image_tag "avatar.png", alt: "avatar", class: "avatar" %>
      </li>
      <li class="btn btn-sell btn-sm mx-2">
        <%= link_to "Sell", new_listing_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>